# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkproduct',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='productpicture',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rentalproduct',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='uniqueproduct',
            name='product_ptr',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='codename',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='qoute',
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BulkProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductPicture',
        ),
        migrations.DeleteModel(
            name='RentalProduct',
        ),
        migrations.DeleteModel(
            name='UniqueProduct',
        ),
    ]
